PowerData <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
PowerData$Date <- as.Date(PowerData$Date, "%d/%m/%Y")
library(dplyr)
Subset_PowerData <- filter(PowerData, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
Subset_PowerData$Full_Time <- as.POSIXlt(paste(Subset_PowerData$Date, Subset_PowerData$Time, sep = " "))
Subset_PowerData$Global_active_power <- as.numeric(Subset_PowerData$Global_active_power, na.rm = TRUE)
Subset_PowerData$Sub_metering_1 <- as.numeric(Subset_PowerData$Sub_metering_1, na.rm = TRUE)
Subset_PowerData$Sub_metering_2 <- as.numeric(Subset_PowerData$Sub_metering_2, na.rm = TRUE)
Subset_PowerData$Sub_metering_3 <- as.numeric(Subset_PowerData$Sub_metering_3, na.rm = TRUE)
png("Plot_3.png", width = 480, height = 480)
with(Subset_PowerData, plot(Full_Time, Sub_metering_1,
                            xlab = "Day", ylab = "Energy Sub Metering", main = "Energy Sub Metering", type = "l"))
lines(Subset_PowerData$Full_Time, Subset_PowerData$Sub_metering_2, col = "red", type = "l")
lines(Subset_PowerData$Full_Time, Subset_PowerData$Sub_metering_3, col = "blue", type = "l")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 2.5, lty = 1)
dev.off()
